require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bins", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Bin. As you add validations to Bin, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bin.create! valid_attributes
      get bins_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bin = Bin.create! valid_attributes
      get bin_url(bin)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bin_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bin = Bin.create! valid_attributes
      get edit_bin_url(bin)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bin" do
        expect {
          post bins_url, params: { bin: valid_attributes }
        }.to change(Bin, :count).by(1)
      end

      it "redirects to the created bin" do
        post bins_url, params: { bin: valid_attributes }
        expect(response).to redirect_to(bin_url(Bin.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bin" do
        expect {
          post bins_url, params: { bin: invalid_attributes }
        }.to change(Bin, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bins_url, params: { bin: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bin" do
        bin = Bin.create! valid_attributes
        patch bin_url(bin), params: { bin: new_attributes }
        bin.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bin" do
        bin = Bin.create! valid_attributes
        patch bin_url(bin), params: { bin: new_attributes }
        bin.reload
        expect(response).to redirect_to(bin_url(bin))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bin = Bin.create! valid_attributes
        patch bin_url(bin), params: { bin: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bin" do
      bin = Bin.create! valid_attributes
      expect {
        delete bin_url(bin)
      }.to change(Bin, :count).by(-1)
    end

    it "redirects to the bins list" do
      bin = Bin.create! valid_attributes
      delete bin_url(bin)
      expect(response).to redirect_to(bins_url)
    end
  end
end
